// prisma/seed.js
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  await prisma.boxer.createMany({
    data: [
      {
        name: 'Aidan Reilly',
        sex: 'Male',
        country: 'Ireland',
        age: 21,
        profileImage: 'https://picsum.photos/200',
        club: 'Crumlin BC',
        province: 'Leinster',
        weight: 57,
        stance: 'Orthodox',
        level: 'Youth',
        fightsWon: 15,
        fightsLost: 2,
        videoUrl: 'https://youtube.com/watch?v=aidan1',
      },
      {
        name: 'Siobhan Clarke',
        sex: 'Female',
        country: 'Ireland',
        age: 23,
        profileImage: 'https://picsum.photos/200',
        club: 'Bray BC',
        province: 'Leinster',
        weight: 60,
        stance: 'Southpaw',
        level: 'Elite',
        fightsWon: 24,
        fightsLost: 3,
        videoUrl: 'https://youtube.com/watch?v=siobhan2',
      },
      {
        name: 'Carleigh Irving',
        sex: 'Female',
        country: 'Ireland',
        age: 19,
        profileImage: 'https://picsum.photos/200',
        club: 'Oakleaf BC',
        province: 'Ulster',
        weight: 48,
        stance: 'Orthodox',
        level: 'Elite',
        fightsWon: 32,
        fightsLost: 6,
        videoUrl: 'https://youtube.com/watch?v=eamon3',
      },
      {
        name: 'Dervla Murray',
        sex: 'Female',
        country: 'Ireland',
        age: 27,
        profileImage: 'https://picsum.photos/200',
        club: 'Smithfield BC',
        province: 'Leinster',
        weight: 75,
        stance: 'Orthodox',
        level: 'Elite',
        fightsWon: 35,
        fightsLost: 8,
        videoUrl: 'https://youtube.com/watch?v=dervla4',
      },
      {
        name: 'Cathal O’Neal',
        sex: 'Male',
        country: 'Ireland',
        age: 19,
        profileImage: 'https://picsum.photos/200',
        club: 'Gorey BC',
        province: 'Leinster',
        weight: 52,
        stance: 'Orthodox',
        level: 'junior',
        fightsWon: 11,
        fightsLost: 3,
        videoUrl: 'https://youtube.com/watch?v=cathal5',
      },
      {
        name: 'Maeve Harte',
        sex: 'Female',
        country: 'Ireland',
        age: 25,
        profileImage: 'https://picsum.photos/200',
        club: 'Spartan BC',
        province: 'Connacht',
        weight: 54,
        stance: 'Southpaw',
        level: 'Elite',
        fightsWon: 29,
        fightsLost: 5,
        videoUrl: 'https://youtube.com/watch?v=maeveh6',
      },
      {
        name: 'Brendan Doran',
        sex: 'Male',
        country: 'Ireland',
        age: 22,
        profileImage: 'https://picsum.photos/200',
        club: 'Trojan BC',
        province: 'Munster',
        weight: 64,
        stance: 'Southpaw',
        level: 'Youth',
        fightsWon: 17,
        fightsLost: 1,
        videoUrl: 'https://youtube.com/watch?v=brendan7',
      },
      {
        name: 'Niamh Casey',
        sex: 'Female',
        country: 'Ireland',
        age: 24,
        profileImage: 'https://picsum.photos/200',
        club: 'Bray BC',
        province: 'Leinster',
        weight: 69,
        stance: 'Orthodox',
        level: 'Elite',
        fightsWon: 20,
        fightsLost: 4,
        videoUrl: 'https://youtube.com/watch?v=niamh8',
      },
      {
        name: 'Padraig Connolly',
        sex: 'Male',
        country: 'Ireland',
        age: 30,
        profileImage: 'https://picsum.photos/200',
        club: 'Crumlin BC',
        province: 'Leinster',
        weight: 81,
        stance: 'Orthodox',
        level: 'Elite',
        fightsWon: 40,
        fightsLost: 8,
        videoUrl: 'https://youtube.com/watch?v=padraig9',
      },
      {
        name: 'Saoirse Byrne',
        sex: 'Female',
        country: 'Ireland',
        age: 26,
        profileImage: 'https://picsum.photos/200',
        club: 'Bray BC',
        province: 'Leinster',
        weight: 57,
        stance: 'Orthodox',
        level: 'junior',
        fightsWon: 19,
        fightsLost: 3,
        videoUrl: 'https://youtube.com/watch?v=saoirse10',
      },
      {
        name: 'Fiachra Healy',
        sex: 'Male',
        country: 'Ireland',
        age: 29,
        profileImage: 'https://picsum.photos/200',
        club: 'Smithfield BC',
        province: 'Leinster',
        weight: 69,
        stance: 'Orthodox',
        level: 'Elite',
        fightsWon: 37,
        fightsLost: 6,
        videoUrl: 'https://youtube.com/watch?v=fiachra11',
      },
      {
        name: 'Orla Hegarty',
        sex: 'Female',
        country: 'Ireland',
        age: 18,
        profileImage: 'https://picsum.photos/200',
        club: 'Oakleaf BC',
        province: 'Ulster',
        weight: 51,
        stance: 'Southpaw',
        level: 'Youth',
        fightsWon: 14,
        fightsLost: 2,
        videoUrl: 'https://youtube.com/watch?v=orlah12',
      },
      {
        name: 'Dara Quinn',
        sex: 'Male',
        country: 'Ireland',
        age: 32,
        profileImage: 'https://picsum.photos/200',
        club: 'Gorey BC',
        province: 'Leinster',
        weight: 75,
        stance: 'Southpaw',
        level: 'Elite',
        fightsWon: 28,
        fightsLost: 5,
        videoUrl: 'https://youtube.com/watch?v=dara13',
      },
      {
        name: 'Eilis Finnegan',
        sex: 'Female',
        country: 'Ireland',
        age: 27,
        profileImage: 'https://picsum.photos/200',
        club: 'Spartan BC',
        province: 'Connacht',
        weight: 64,
        stance: 'Orthodox',
        level: 'Elite',
        fightsWon: 36,
        fightsLost: 4,
        videoUrl: 'https://youtube.com/watch?v=eilis14',
      },
      {
        name: 'Kieran Malone',
        sex: 'Male',
        country: 'Ireland',
        age: 20,
        profileImage: 'https://picsum.photos/200',
        club: 'Crumlin BC',
        province: 'Leinster',
        weight: 48,
        stance: 'Orthodox',
        level: 'junior',
        fightsWon: 11,
        fightsLost: 1,
        videoUrl: 'https://youtube.com/watch?v=kieran15',
      },
      {
        name: 'Rosin Dowling',
        sex: 'Female',
        country: 'Ireland',
        age: 25,
        profileImage: 'https://picsum.photos/200',
        club: 'Bray BC',
        province: 'Leinster',
        weight: 60,
        stance: 'Orthodox',
        level: 'Elite',
        fightsWon: 25,
        fightsLost: 7,
        videoUrl: 'https://youtube.com/watch?v=rosin16',
      },
      {
        name: 'Ciaran Hughes',
        sex: 'Male',
        country: 'Ireland',
        age: 31,
        profileImage: 'https://picsum.photos/200',
        club: 'Trojan BC',
        province: 'Munster',
        weight: 81,
        stance: 'Southpaw',
        level: 'Elite',
        fightsWon: 42,
        fightsLost: 10,
        videoUrl: 'https://youtube.com/watch?v=ciaran17',
      },
      {
        name: 'Nuala Casey',
        sex: 'Female',
        country: 'Ireland',
        age: 22,
        profileImage: 'https://picsum.photos/200',
        club: 'Oakleaf BC',
        province: 'Ulster',
        weight: 69,
        stance: 'Southpaw',
        level: 'Youth',
        fightsWon: 16,
        fightsLost: 2,
        videoUrl: 'https://youtube.com/watch?v=nuala18',
      },
      {
        name: 'Tadhg Harrington',
        sex: 'Male',
        country: 'Ireland',
        age: 24,
        profileImage: 'https://picsum.photos/200',
        club: 'Spartan BC',
        province: 'Connacht',
        weight: 91,
        stance: 'Orthodox',
        level: 'Elite',
        fightsWon: 39,
        fightsLost: 6,
        videoUrl: 'https://youtube.com/watch?v=tadhg19',
      },
      {
        name: 'Aoife Cleary',
        sex: 'Female',
        country: 'Ireland',
        age: 19,
        profileImage: 'https://picsum.photos/200',
        club: 'Gorey BC',
        province: 'Leinster',
        weight: 54,
        stance: 'Orthodox',
        level: 'junior',
        fightsWon: 13,
        fightsLost: 1,
        videoUrl: 'https://youtube.com/watch?v=aoife20',
      },
    ],
  });
  await prisma.contest.createMany({
    data: [
      {
        date: new Date('2023-01-10T10:00:00Z'),
        boxer1Id: 1,
        boxer2Id: 2,
        winnerId: 1,
        result: 'Aidan Reilly won',
      },
      {
        date: new Date('2023-02-15T14:30:00Z'),
        boxer1Id: 3,
        boxer2Id: 4,
        winnerId: 4,
        result: 'Dervla Murray won',
      },
      {
        date: new Date('2023-03-05T12:00:00Z'),
        boxer1Id: 5,
        boxer2Id: 6,
        winnerId: 6,
        result: 'Maeve Harte won',
      },
      {
        date: new Date('2023-03-20T18:45:00Z'),
        boxer1Id: 7,
        boxer2Id: 8,
        winnerId: 7,
        result: 'Brendan Doran won',
      },
      {
        date: new Date('2023-04-01T20:00:00Z'),
        boxer1Id: 9,
        boxer2Id: 10,
        winnerId: 10,
        result: 'Saoirse Byrne won',
      },
      {
        date: new Date('2023-04-10T15:30:00Z'),
        boxer1Id: 11,
        boxer2Id: 12,
        winnerId: 11,
        result: 'Fiachra Healy won',
      },
      {
        date: new Date('2023-04-25T17:00:00Z'),
        boxer1Id: 13,
        boxer2Id: 14,
        winnerId: 13,
        result: 'Dara Quinn won',
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
